id = "moonbug-debugger"
name = "moonbug"
description = "Single-file, in-process, DAP powered Lua debugger for your favorite code editor!"
version = "0.1.0"
schema_version = 1
authors = ["Christopher Kaster <me@atomicptr.de>"]
repository = "https://github.com/atomicptr/zed-moonbug"

[debug_adapters.moonbug]
schema_path = "schemas/moonbug.json"
